import { ToolMeta } from './types';

export const PDF_TOOLS: ToolMeta[] = [
  {
    id: 'merge-pdf',
    title: 'Merge PDF',
    tagline: 'Combine multiple PDFs into a single document in any order.',
    description: 'Combine two or more PDF files into a single document. Drag and drop to reorder pages and files before merging. Fast and browser-local.',
    category: 'pdf',
    path: '/pdf/merge-pdf',
    iconName: 'Files',
    accept: '.pdf,application/pdf',
    acceptExtensions: ['.pdf'],
  },
  {
    id: 'split-pdf',
    title: 'Split PDF',
    tagline: 'Extract specific pages or page ranges from any PDF document.',
    description: 'Extract individual pages or custom page ranges (e.g. 1-3, 5, 8-10) into a new independent PDF. No file size limits on your local device.',
    category: 'pdf',
    path: '/pdf/split-pdf',
    iconName: 'Scissors',
    accept: '.pdf,application/pdf',
    acceptExtensions: ['.pdf'],
  },
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    tagline: 'Reduce PDF file size by stripping redundant streams and metadata.',
    description: 'Optimize PDF file size client-side. Cleans unused objects, compresses internal streams, and optimizes file overhead without uploading your data.',
    category: 'pdf',
    path: '/pdf/compress-pdf',
    iconName: 'Minimize2',
    accept: '.pdf,application/pdf',
    acceptExtensions: ['.pdf'],
  },
  {
    id: 'jpg-to-pdf',
    title: 'JPG to PDF',
    tagline: 'Convert JPG images to high-quality PDF documents with layout control.',
    description: 'Turn your JPG photos and scans into a single organized PDF. Adjust orientation, margins, and paper sizes with real-time browser generation.',
    category: 'pdf',
    path: '/pdf/jpg-to-pdf',
    iconName: 'FileImage',
    accept: '.jpg,.jpeg,image/jpeg',
    acceptExtensions: ['.jpg', '.jpeg'],
  },
];

export const IMAGE_TOOLS: ToolMeta[] = [
  {
    id: 'compress-image',
    title: 'Compress Image',
    tagline: 'Shrink JPG, PNG, and WebP images with adjustable quality settings.',
    description: 'Reduce image file size with fine-grained visual quality control. Preview file size reduction and quality comparisons directly in your browser.',
    category: 'image',
    path: '/image/compress-image',
    iconName: 'ImageDown',
    accept: '.jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp',
    acceptExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'resize-image',
    title: 'Resize Image',
    tagline: 'Scale image dimensions by exact pixels or percentage with aspect lock.',
    description: 'Quickly resize photos for social media, web, or print. Lock aspect ratio, select from popular presets, and export in your preferred format.',
    category: 'image',
    path: '/image/resize-image',
    iconName: 'Scaling',
    accept: '.jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp',
    acceptExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'jpg-to-png',
    title: 'JPG to PNG',
    tagline: 'Convert JPEG images to lossless PNG format instantly.',
    description: 'Convert JPG pictures to crisp PNG files. Pure client-side canvas rendering ensures zero compression artifacts and immediate downloads.',
    category: 'image',
    path: '/image/jpg-to-png',
    iconName: 'Repeat',
    accept: '.jpg,.jpeg,image/jpeg',
    acceptExtensions: ['.jpg', '.jpeg'],
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    tagline: 'Convert mixed images (JPG, PNG, WebP) into an organized PDF file.',
    description: 'Combine multiple image files of any format into one PDF document. Reorder images, customize page orientation, and generate PDFs in seconds.',
    category: 'image',
    path: '/image/image-to-pdf',
    iconName: 'FileStack',
    accept: '.jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp',
    acceptExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
  },
];

export const ALL_TOOLS: ToolMeta[] = [...PDF_TOOLS, ...IMAGE_TOOLS];
